const crypto = require('node:crypto')
const os = require('node:os')
const { InstanceBase, InstanceStatus } = require('@companion-module/base')
const UpgradeScripts = require('./upgrades')
const UpdateActions = require('./actions')
const UpdateFeedbacks = require('./feedbacks')
const UpdatePresets = require('./presets')
const UpdateVariableDefinitions = require('./variables')
const { SLVideoTcpClient, SLVIDEO_PORT, SD_MESSAGE_TYPES, parseStructuredData } = require('./tcp')

const DEFAULT_BACKGROUND = '#1f1f1f'
const DEFAULT_FOREGROUND = '#ffffff'
const DISCONNECTED_BACKGROUND = '#7f1d1d'
const DEFAULT_GRID_COLUMNS = 8
const DEFAULT_GRID_ROWS = 4
const GRID_SIZE_RESEND_DELAY_MS = 1000

function createHardwareId(instanceId) {
	const source = [os.hostname(), String(os.availableParallelism?.() ?? os.cpus().length), instanceId].join('-')

	return crypto.createHash('sha1').update(source).digest('hex')
}

function parsePositiveInteger(value) {
	const parsed = Number(value)
	return Number.isInteger(parsed) && parsed > 0 ? parsed : null
}

function colorToInt(hex) {
	return parseInt(String(hex).replace(/^#/, ''), 16) || 0
}

function makeGridSlotKey(row, column) {
	if (!Number.isFinite(row) || !Number.isFinite(column)) {
		return ''
	}

	return `${row}:${column}`
}

function extractShortcuts(payload) {
	const pageData = parseStructuredData(payload)
	if (!pageData || typeof pageData !== 'object' || Array.isArray(pageData)) {
		return []
	}

	const page = Number(pageData.Page) || 0
	const pageShortcuts = Array.isArray(pageData.Shortcuts) ? pageData.Shortcuts : []
	const shortcuts = []

	for (const rawShortcut of pageShortcuts) {
		if (!rawShortcut || typeof rawShortcut !== 'object') {
			continue
		}

		const guid = String(rawShortcut.Guid ?? '')
		if (!guid) {
			continue
		}

		const position = rawShortcut.Position
		const row = Number(position?.row)
		const column = Number(position?.column)
		const iconBase64 = String(rawShortcut.IconBase64 ?? '').trim()

		shortcuts.push({
			guid,
			name: String(rawShortcut.Name ?? guid),
			type: String(rawShortcut.Type ?? ''),
			hasIcon: rawShortcut.HasIcon === true,
			iconBase64: iconBase64 ? iconBase64.replace(/^data:image\/png;base64,/i, '') : undefined,
			backColor: String(rawShortcut.BackColor ?? DEFAULT_BACKGROUND),
			foreColor: String(rawShortcut.ForeColor ?? DEFAULT_FOREGROUND),
			position: Number.isFinite(row) && Number.isFinite(column) ? { page, row, column } : null,
			index: shortcuts.length,
		})
	}

	return shortcuts
}

function parseGridSize(payload) {
	const parsedValue = parseStructuredData(payload)
	if (!parsedValue || typeof parsedValue !== 'object' || Array.isArray(parsedValue)) {
		return null
	}

	const columns = parsePositiveInteger(parsedValue.Columns)
	const rows = parsePositiveInteger(parsedValue.Rows)
	if (columns === null || rows === null) {
		return null
	}

	return { columns, rows }
}

class ModuleInstance extends InstanceBase {
	constructor(internal) {
		super(internal)

		this.config = {}
		this.hardwareId = createHardwareId(this.id)
		this.shortcuts = []
		this.shortcutsByGuid = new Map()
		this.shortcutsByGridSlot = new Map()
		this.gridSize = null
		this.gridSizeRetryTimer = undefined
		this.lastTriggeredShortcut = null
		this.shortcutSlotCount = 0
		this.client = new SLVideoTcpClient({
			hardwareId: this.hardwareId,
			port: SLVIDEO_PORT,
			log: this.log.bind(this),
			onConnected: this.handleSocketConnected.bind(this),
			onDisconnected: this.handleSocketDisconnected.bind(this),
			onMessage: this.handleSocketMessage.bind(this),
		})
	}

	async init(config) {
		this.config = config
		this.gridSize = this.getPreferredGridSize()

		this.updateActions()
		this.updateFeedbacks()
		this.updatePresets()
		this.updateVariableDefinitions()
		this.refreshVariableValues()
		this.connectToServer()
	}

	async destroy() {
		this.clearGridSizeRetryTimer()
		this.client.destroy()
	}

	async configUpdated(config) {
		this.config = config
		this.gridSize = this.getPreferredGridSize()
		this.updateActions()
		this.updateFeedbacks()
		this.connectToServer()
		this.updatePresets()
		this.updateVariableDefinitions()
		this.refreshVariableValues()
		this.checkFeedbacks('shortcut_property', 'shortcut_available', 'disconnected')
		if (this.client.isConnected) {
			this.sendGridSize()
		}
	}

	getConfigFields() {
		return [
			{
				type: 'textinput',
				id: 'host',
				label: 'SLVideo host',
				width: 8,
				default: '127.0.0.1',
			},
			{
				type: 'static-text',
				id: 'port_info',
				label: 'TCP port',
				width: 4,
				value: String(SLVIDEO_PORT),
			},
			{
				type: 'static-text',
				id: 'auth_info',
				label: 'Authentication',
				width: 12,
				value: `Hardware ID generated by this Companion instance and sent as ${this.hardwareId}3`,
			},
			{
				type: 'number',
				id: 'gridColumns',
				label: 'Grid columns',
				width: 6,
				default: DEFAULT_GRID_COLUMNS,
				min: 1,
				max: 32,
			},
			{
				type: 'number',
				id: 'gridRows',
				label: 'Grid rows',
				width: 6,
				default: DEFAULT_GRID_ROWS,
				min: 1,
				max: 32,
			},
		]
	}

	getConfiguredHost() {
		return String(this.config.host ?? '').trim()
	}

	connectToServer() {
		const host = this.getConfiguredHost()

		if (!host) {
			this.client.disconnect()
			this.updateStatus(InstanceStatus.BadConfig, 'Enter the SLVideo host')
			return
		}

		this.updateStatus(InstanceStatus.Connecting, `Connecting to ${host}:${SLVIDEO_PORT}`)
		this.client.connect(host)
	}

	handleSocketConnected() {
		const host = this.getConfiguredHost()
		this.updateStatus(InstanceStatus.Ok, host ? `Connected to ${host}:${SLVIDEO_PORT}` : 'Connected')
		this.clearGridSizeRetryTimer()
		this.sendGridSize()
		this.requestShortcutLists()
		this.refreshVariableValues()
		this.checkFeedbacks('shortcut_property', 'shortcut_available', 'disconnected')
		this.subscribeActions('trigger_shortcut')
	}

	handleSocketDisconnected(reason) {
		this.clearGridSizeRetryTimer()
		if (!this.getConfiguredHost()) {
			this.updateStatus(InstanceStatus.BadConfig, 'Enter the SLVideo host')
		} else {
			this.updateStatus(InstanceStatus.ConnectionFailure, reason || 'SLVideo connection closed')
		}

		this.refreshVariableValues()
		this.checkFeedbacks('shortcut_property', 'shortcut_available', 'disconnected')
	}

	handleSocketMessage(message) {
		const payload = parseStructuredData(message)
		if (!payload || typeof payload !== 'object') {
			return
		}

		switch (payload.messageType) {
			case SD_MESSAGE_TYPES.SET_SHORTCUT_LISTS: {
				const shortcuts = extractShortcuts(payload.message)
				this.updateShortcutCache(shortcuts)
				break
			}
			case SD_MESSAGE_TYPES.SHORTCUTS_OUT_OF_SYNC:
				this.requestShortcutLists()
				break
			case SD_MESSAGE_TYPES.SET_GRID_SIZE: {
				this.gridSize = parseGridSize(payload.message)
				this.updateActions()
				this.updateFeedbacks()
				this.updatePresets()
				this.updateVariableDefinitions()
				this.refreshVariableValues()
				break
			}
			default:
				break
		}
	}

	updateShortcutCache(shortcuts) {
		const previousShortcutCount = this.shortcuts.length
		this.shortcuts = Array.isArray(shortcuts) ? shortcuts : []
		this.shortcutsByGuid = new Map(this.shortcuts.map((shortcut) => [shortcut.guid, shortcut]))
		this.shortcutsByGridSlot = new Map(
			this.shortcuts
				.filter((shortcut) => shortcut.position)
				.map((shortcut) => [makeGridSlotKey(shortcut.position.row, shortcut.position.column), shortcut]),
		)

		if (this.lastTriggeredShortcut && !this.shortcutsByGuid.has(this.lastTriggeredShortcut.guid)) {
			this.lastTriggeredShortcut = null
		}

		this.updateActions()
		this.updateFeedbacks()
		this.updatePresets()
		if (previousShortcutCount !== this.shortcuts.length) {
			this.updateVariableDefinitions()
		}
		this.refreshVariableValues()
		this.checkFeedbacks('shortcut_property', 'shortcut_available', 'disconnected')
	}

	requestShortcutLists() {
		return this.client.sendStreamDeckMessage(SD_MESSAGE_TYPES.GET_SHORTCUT_LISTS)
	}

	getPreferredGridSize() {
		const configuredColumns = parsePositiveInteger(this.config.gridColumns)
		const configuredRows = parsePositiveInteger(this.config.gridRows)

		return {
			columns: configuredColumns ?? DEFAULT_GRID_COLUMNS,
			rows: configuredRows ?? DEFAULT_GRID_ROWS,
		}
	}

	clearGridSizeRetryTimer() {
		if (this.gridSizeRetryTimer) {
			clearTimeout(this.gridSizeRetryTimer)
			this.gridSizeRetryTimer = undefined
		}
	}

	scheduleGridSizeRetry() {
		this.clearGridSizeRetryTimer()
		this.gridSizeRetryTimer = setTimeout(() => {
			this.gridSizeRetryTimer = undefined
			if (!this.client.isConnected) {
				return
			}

			this.sendGridSize(false)
		}, GRID_SIZE_RESEND_DELAY_MS)
	}

	sendGridSize(scheduleRetry = true) {
		this.gridSize = this.getPreferredGridSize()

		const payload = JSON.stringify({
			Rows: this.gridSize.rows,
			Columns: this.gridSize.columns,
		})

		const sent = this.client.sendStreamDeckMessage(SD_MESSAGE_TYPES.SET_GRID_SIZE, payload)
		if (sent && scheduleRetry) {
			this.scheduleGridSizeRetry()
		}

		return sent
	}

	getGridColumns() {
		return Number(this.getPreferredGridSize().columns)
	}

	getGridRows() {
		return Number(this.getPreferredGridSize().rows)
	}

	getShortcutOptionFields(defaultOptions = {}) {
		const rowDefault = Number.isInteger(defaultOptions?.row) ? defaultOptions.row : -1
		const columnDefault = Number.isInteger(defaultOptions?.column) ? defaultOptions.column : -1
		const defaultShortcutId = String(defaultOptions?.shortcutId ?? '')
		const shortcutChoices = this.shortcuts.map((shortcut) => {
			const positionLabel = shortcut.position ? ` [${shortcut.position.row}/${shortcut.position.column}]` : ''
			return {
				id: shortcut.guid,
				label: `${shortcut.name} (${shortcut.type})${positionLabel}`,
			}
		})

		const choices = [{ id: '', label: 'Automatic by row/column' }, ...shortcutChoices]
		const defaultChoice = choices.some((choice) => choice.id === defaultShortcutId) ? defaultShortcutId : ''

		return [
			{
				id: 'shortcut_help',
				type: 'static-text',
				label: 'Selection',
				value: 'Use row/column to follow the SLVideo grid, or pick a specific shortcut.',
			},
			{
				id: 'shortcutId',
				type: 'dropdown',
				label: 'SLVideo shortcut',
				choices,
				default: defaultChoice,
			},
			{
				id: 'row',
				type: 'number',
				label: 'SLVideo row',
				default: rowDefault,
				min: -1,
				max: Math.max(this.getGridRows() - 1, -1),
			},
			{
				id: 'column',
				type: 'number',
				label: 'SLVideo column',
				default: columnDefault,
				min: -1,
				max: Math.max(this.getGridColumns() - 1, -1),
			},
		]
	}

	getConfiguredGridPosition(options) {
		const row = Number(options?.row)
		const column = Number(options?.column)

		if (!Number.isInteger(row) || !Number.isInteger(column)) {
			return null
		}

		if (row < 0 || column < 0) {
			return null
		}

		return {
			row,
			column,
		}
	}

	getShortcutForGridPosition(position) {
		if (!position) {
			return null
		}

		return this.shortcutsByGridSlot.get(makeGridSlotKey(position.row, position.column)) ?? null
	}

	getShortcutForControl(controlId, options) {
		const shortcutId = String(options?.shortcutId ?? '').trim()
		if (shortcutId) {
			return this.getShortcutByGuid(shortcutId) ?? null
		}

		const configuredPosition = this.getConfiguredGridPosition(options)
		if (configuredPosition) {
			return this.getShortcutForGridPosition(configuredPosition)
		}
		return null
	}

	triggerShortcutForControl(controlId, options) {
		const shortcut = this.getShortcutForControl(controlId, options)
		if (!shortcut) {
			return false
		}

		return this.startShortcut(shortcut.guid)
	}

	getShortcutByGuid(guid) {
		return this.shortcutsByGuid.get(String(guid ?? ''))
	}

	startShortcut(guid) {
		const shortcutGuid = String(guid ?? '')
		if (!shortcutGuid) {
			return false
		}

		const sent = this.client.sendStreamDeckMessage(SD_MESSAGE_TYPES.START_SHORTCUT, JSON.stringify(shortcutGuid))
		if (sent) {
			const shortcut = this.getShortcutByGuid(shortcutGuid)
			this.lastTriggeredShortcut = {
				guid: shortcutGuid,
				name: shortcut?.name ?? '',
			}
			this.refreshVariableValues()
		}

		return sent
	}

	formatShortcutText(shortcut) {
		const name = String(shortcut.name ?? '').trim() || 'Untitled'
		if (shortcut.type === 'Event') {
			return `⚡\n${name}`
		}

		return name
	}

	getShortcutTextForGridPosition(position) {
		const shortcut = this.getShortcutForGridPosition(position)
		if (!shortcut || (shortcut.hasIcon && shortcut.iconBase64)) {
			return ''
		}

		return this.formatShortcutText(shortcut)
	}

	getShortcutStyleForControl(controlId, options) {
		const shortcut = this.getShortcutForControl(controlId, options)

		if (!this.client.isConnected) {
			const position = shortcut?.position ?? this.getConfiguredGridPosition(options)
			return {
				text: position ? `Disconnected\n${position.row}/${position.column}` : 'Disconnected',
				color: colorToInt(DEFAULT_FOREGROUND),
				bgcolor: colorToInt(DISCONNECTED_BACKGROUND),
				icon: null,
			}
		}

		const icon = shortcut?.hasIcon && shortcut.iconBase64 ? shortcut.iconBase64 : null
		return {
			text: shortcut && !icon ? this.formatShortcutText(shortcut) : '',
			color: colorToInt(shortcut?.foreColor || DEFAULT_FOREGROUND),
			bgcolor: colorToInt(shortcut?.backColor || DEFAULT_BACKGROUND),
			icon,
		}
	}

	buildVariableDefinitions() {
		const definitions = {
			connection_state: { name: 'Connection state' },
			hardware_id: { name: 'Hardware ID used for authentication' },
			shortcut_count: { name: 'Number of received shortcuts' },
			grid_columns: { name: 'Remote grid column count' },
			grid_rows: { name: 'Remote grid row count' },
			last_shortcut_guid: { name: 'GUID of the last triggered shortcut' },
			last_shortcut_name: { name: 'Name of the last triggered shortcut' },
			shortcut_cache_json: { name: 'Raw JSON cache of known shortcuts' },
		}

		for (let row = 0; row < this.getGridRows(); row++) {
			for (let column = 0; column < this.getGridColumns(); column++) {
				definitions[`slot_${row}_${column}_text`] = { name: `Button text for row ${row} / column ${column}` }
			}
		}

		for (const [index, shortcut] of this.shortcuts.entries()) {
			const slot = index + 1
			definitions[`shortcut_${slot}_guid`] = { name: `Shortcut ${slot} GUID` }
			definitions[`shortcut_${slot}_name`] = { name: `Shortcut ${slot} name` }
			definitions[`shortcut_${slot}_type`] = { name: `Shortcut ${slot} type` }
			definitions[`shortcut_${slot}_row`] = { name: `Shortcut ${slot} row` }
			definitions[`shortcut_${slot}_column`] = { name: `Shortcut ${slot} column` }
			definitions[`shortcut_${slot}_has_icon`] = { name: `Shortcut ${slot} has icon` }
			definitions[`shortcut_${slot}_backcolor`] = { name: `Shortcut ${slot} background color` }
			definitions[`shortcut_${slot}_forecolor`] = { name: `Shortcut ${slot} text color` }
		}

		return definitions
	}

	refreshVariableValues() {
		const currentGridSize = this.getPreferredGridSize()
		const previousSlotCount = this.shortcutSlotCount
		const values = {
			connection_state: this.client.isConnected ? 'connected' : 'disconnected',
			hardware_id: this.hardwareId,
			shortcut_count: this.shortcuts.length,
			grid_columns: currentGridSize.columns,
			grid_rows: currentGridSize.rows,
			last_shortcut_guid: this.lastTriggeredShortcut?.guid ?? '',
			last_shortcut_name: this.lastTriggeredShortcut?.name ?? '',
			shortcut_cache_json: JSON.stringify(this.shortcuts),
		}

		for (let row = 0; row < currentGridSize.rows; row++) {
			for (let column = 0; column < currentGridSize.columns; column++) {
				values[`slot_${row}_${column}_text`] = this.getShortcutTextForGridPosition({ row, column })
			}
		}

		for (const [index, shortcut] of this.shortcuts.entries()) {
			const slot = index + 1
			values[`shortcut_${slot}_guid`] = shortcut.guid
			values[`shortcut_${slot}_name`] = shortcut.name
			values[`shortcut_${slot}_type`] = shortcut.type
			values[`shortcut_${slot}_row`] = shortcut.position?.row ?? ''
			values[`shortcut_${slot}_column`] = shortcut.position?.column ?? ''
			values[`shortcut_${slot}_has_icon`] = shortcut.hasIcon ? 'true' : 'false'
			values[`shortcut_${slot}_backcolor`] = shortcut.backColor
			values[`shortcut_${slot}_forecolor`] = shortcut.foreColor
		}

		for (let slot = this.shortcuts.length + 1; slot <= previousSlotCount; slot += 1) {
			values[`shortcut_${slot}_guid`] = ''
			values[`shortcut_${slot}_name`] = ''
			values[`shortcut_${slot}_type`] = ''
			values[`shortcut_${slot}_row`] = ''
			values[`shortcut_${slot}_column`] = ''
			values[`shortcut_${slot}_has_icon`] = ''
			values[`shortcut_${slot}_backcolor`] = ''
			values[`shortcut_${slot}_forecolor`] = ''
		}

		this.shortcutSlotCount = this.shortcuts.length
		this.setVariableValues(values)
	}

	updateActions() {
		UpdateActions(this)
	}

	updateFeedbacks() {
		UpdateFeedbacks(this)
	}

	updatePresets() {
		UpdatePresets(this)
	}

	updateVariableDefinitions() {
		UpdateVariableDefinitions(this)
	}
}

export default ModuleInstance
export { UpgradeScripts }
